import { useEffect, useState, useRef, lazy, Suspense } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, FileText, FolderOpen, ShieldCheck, Settings, CircleHelp, Search, Upload, Trash2, ChevronLeft, ChevronRight, Download, X, Check, AlertTriangle, LoaderCircle, Sparkles } from 'lucide-react';
const EvidenceScene=lazy(()=>import('./EvidenceScene'));
type Doc={id:string;name:string;page_count:number;status:string;error?:string|null;created_at:string};
type Evidence={id:string;page:number;text:string;score:number};
type Claim={text:string;status:string;evidence_ids:string[];pages:number[];method:string;explanation:string;warnings:string[]};
type Result={id:string;answer:string;claims:Claim[];evidence:Evidence[];metrics:Record<string,number>;created_at:string;question:string;mode:string};
const nav=[['Overview','overview'],['Documents','documents'],['Ask & Verify','ask'],['Reports','reports'],['Settings','settings']] as const;
const API='/api';
async function request<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(API+path,init);if(!r.ok){const b=await r.json().catch(()=>({detail:r.statusText}));throw new Error(b.detail||'Request failed');}return r.json();}
export default function App(){
 const [section,setSection]=useState('overview'),[docs,setDocs]=useState<Doc[]>([]),[active,setActive]=useState(''),[doc,setDoc]=useState<(Doc&{pages:{number:number;text:string}[]})|null>(null),[page,setPage]=useState(1),[sourceMode,setSourceMode]=useState<'pdf'|'text'>('pdf'),[question,setQuestion]=useState(''),[result,setResult]=useState<Result|null>(null),[selected,setSelected]=useState<number|null>(null),[reports,setReports]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[health,setHealth]=useState<any>(null),[search,setSearch]=useState(''); const reduced=useReducedMotion(); const uploadInput=useRef<HTMLInputElement>(null);
 const refresh=()=>request<Doc[]>('/documents').then(setDocs).catch(e=>setError(e.message));
 useEffect(()=>{refresh();request('/health').then(setHealth).catch(()=>setHealth({status:'offline'}));request<any[]>('/reports').then(setReports).catch(()=>{});},[]);
 useEffect(()=>{if(active)request<any>(`/documents/${active}`).then(x=>{setDoc(x);setPage(1);setSourceMode('pdf')}).catch(e=>setError(e.message));else setDoc(null)},[active]);
 const upload=async(file?:File)=>{if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const d=await request<Doc>('/documents',{method:'POST',body:form});await refresh();setActive(d.id);setSection('ask');}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const ask=async()=>{if(!active||question.trim().length<3)return;setBusy(true);setError('');setResult(null);setSelected(null);try{const r=await request<Result>('/questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document_id:active,question})});setResult(r);setReports(await request<any[]>('/reports'));}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const remove=async(id:string)=>{try{await request(`/documents/${id}`,{method:'DELETE'});if(active===id)setActive('');await refresh()}catch(e){setError((e as Error).message)}};
 const cls=(status:string)=>status.replace(/_/g,' ');
 const currentDoc=docs.find(d=>d.id===active);
 const scenePhase=busy?'processing':result?(result.claims.some(c=>c.status==='contradicted')?'conflict':result.claims.every(c=>c.status==='unverified')?'insufficient':selected!==null?'review':'evidence'):active?'selected':docs.length?'library':'idle';
 const scenePhaseLabel=({processing:'SOURCE PROCESSING',conflict:'CONFLICT DETECTED',insufficient:'EVIDENCE INSUFFICIENT',review:'CLAIM UNDER REVIEW',evidence:'EVIDENCE RETRIEVED',selected:'SOURCE SELECTED',library:'LIBRARY READY',idle:'AWAITING SOURCE'} as const)[scenePhase];
 return <div className="app-shell"><input ref={uploadInput} className="global-upload" type="file" accept="application/pdf,.pdf" onChange={e=>{upload(e.target.files?.[0]);e.currentTarget.value=''}}/><header className="topbar"><button className="brand" onClick={()=>setSection('overview')}><span className="brand-mark"><span/><span/><span/></span><span>prooflayer<small>RESEARCH SYSTEMS</small></span></button><div className="top-context"><span className="live-dot"/> DOCUMENT INTELLIGENCE <i>/</i> {import.meta.env.PROD?'PUBLIC SHARED WORKSPACE':'LOCAL WORKSPACE'}</div><div className="top-right"><span className="api-status"><span className="status-dot"/>{health?.status==='ok'?'API CONNECTED':health?.status==='degraded'?'API DEGRADED':'API OFFLINE'}</span><button className="avatar" aria-label="Workspace">PL</button></div></header>
 <div className="layout"><aside className="rail"><div className="rail-main">{nav.map(([label,id],i)=><button key={id} className={`nav-item ${section===id?'active':''}`} onClick={()=>setSection(id)}><span className="nav-index">0{i+1}</span>{i===0?<ShieldCheck size={16}/>:i===1?<FolderOpen size={16}/>:i===2?<CircleHelp size={16}/>:i===3?<FileText size={16}/>:<Settings size={16}/>}<span>{label}</span>{section===id&&<i/>}</button>)}</div><div className="rail-bottom"><div className="quota"><span>DOCUMENT LIBRARY</span><b>{docs.length.toString().padStart(2,'0')} <small>documents</small></b><div className="quota-line"><i style={{width:`${Math.min(docs.length*10,100)}%`}}/></div></div><div className="rail-user"><div className="user-glyph">PL</div><span>{import.meta.env.PROD?'Shared workspace':'Local workspace'}<small>{import.meta.env.PROD?'PUBLIC ACCESS':'LOCAL SESSION'}</small></span><button aria-label="Settings" onClick={()=>setSection('settings')}><Settings size={15}/></button></div></div></aside>
 <main className="main">
 <AnimatePresence mode="wait"><motion.div key={section} initial={reduced?false:{opacity:0,y:7}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}} transition={{duration:.22}} className="view">
 {section==='overview'&&<><div className="eyebrow"><span>PROOFLAYER / 01</span><span className="line"/><span>DOCUMENT ASSURANCE</span></div><div className="hero-grid"><div className="hero-copy"><div className="hero-kicker"><span className="kicker-mark">01</span> A CLEARER STANDARD FOR AI</div><h1>Every answer<br/>has <em>evidence.</em></h1><p className="hero-sub">Ask what matters. Trace every response to the page it came from. Inspect each claim before you rely on it.</p><div className="hero-actions"><button className="button-primary" onClick={()=>{setSection('documents');uploadInput.current?.click()}}>Analyze a document <ArrowUpRight size={16}/></button><button className="button-link" onClick={()=>document.getElementById('workflow')?.scrollIntoView({behavior:'smooth'})}>Explore the workflow <span>↓</span></button></div><div className="hero-rule"/><div className="hero-meta"><span><b>01</b> UPLOAD SOURCE</span><span><b>02</b> ASK WITH CONTEXT</span><span><b>03</b> CHECK EACH CLAIM</span></div></div><div className={`scene-wrap scene-${scenePhase}`}><div className="scene-label"><span>FIG. 01</span> EVIDENCE ALIGNMENT <span className="scene-live">{scenePhaseLabel}</span></div><Suspense fallback={<div className="scene-fallback"><FileText/><span>Loading evidence model</span></div>}><EvidenceScene phase={scenePhase} evidenceCount={result?.evidence.length||0}/></Suspense><div className="scene-caption"><span>{currentDoc?currentDoc.name.toUpperCase():docs.length?`${docs.length.toString().padStart(2,"0")} SOURCES IN LIBRARY`:"SOURCE LAYER"}</span><span>{result?`${result.claims.length.toString().padStart(2,"0")} CLAIMS / ${(result.evidence.length).toString().padStart(2,"0")} PASSAGES`:"SOURCE / CLAIM / EVIDENCE"}</span><span>STATE / {scenePhaseLabel}</span></div></div></div><div id="workflow" className="workflow"><div className="section-label"><span>THE METHOD</span><span>THREE STEPS / ONE TRACEABLE ANSWER</span></div><div className="workflow-grid">{[['01','Extract','Page-aware text extraction keeps every passage attached to its source.'],['02','Retrieve','Relevant passages are selected from your document for each question.'],['03','Verify','Claims are checked independently; conflicts and gaps remain visible.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><ArrowUpRight size={15}/></article>)}</div></div><div className="bottom-cta"><div><span className="eyebrow-small">START WITH A SOURCE</span><h2>Bring the document.<br/><em>Keep the proof.</em></h2></div><button className="button-primary" onClick={()=>{setSection('documents');uploadInput.current?.click()}}>Analyze a document <ArrowUpRight size={16}/></button></div></>}
 {section==='documents'&&<><div className="eyebrow"><span>LIBRARY / 02</span><span className="line"/><span>YOUR SOURCES</span></div><div className="page-heading"><div><span className="overline">DOCUMENT LIBRARY</span><h1>Sources, <em>in context.</em></h1><p>Private documents are stored locally and processed into page-linked passages.</p></div><label className="button-primary upload-btn"><Upload size={16}/> Upload PDF<input id="file-input" type="file" accept="application/pdf,.pdf" onChange={e=>upload(e.target.files?.[0])}/></label></div><div className="library-tools"><label><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a document"/></label><span>{docs.length} DOCUMENT{docs.length===1?'':'S'}</span></div>{docs.filter(d=>d.name.toLowerCase().includes(search.toLowerCase())).length===0?<div className="empty"><FileText size={27}/><h3>Your source library is clear.</h3><p>Upload a text-based PDF to start asking document-grounded questions.</p><label className="button-secondary">Choose PDF<input type="file" accept="application/pdf,.pdf" onChange={e=>upload(e.target.files?.[0])}/></label></div>:<div className="doc-table"><div className="table-head"><span>DOCUMENT</span><span>STATUS</span><span>PAGES</span><span>ADDED</span><span/></div>{docs.filter(d=>d.name.toLowerCase().includes(search.toLowerCase())).map((d)=><div className="doc-row" key={d.id}><span className="doc-name"><span className="file-icon"><FileText size={17}/></span><span><b>{d.name}</b><small>DOC / {d.id.slice(0,8).toUpperCase()}</small></span></span><span className={`state ${d.status}`}>{d.status==='ready'?<Check size={13}/>:<AlertTriangle size={13}/>} {d.status.replace('_',' ')}</span><span className="mono">{d.page_count.toString().padStart(2,'0')} pp</span><span className="mono">{new Date(d.created_at).toLocaleDateString()}</span><span className="row-actions"><button title="Ask about document" onClick={()=>{setActive(d.id);setSection('ask')}}><ArrowUpRight size={16}/></button><button title="Delete document" onClick={()=>remove(d.id)}><Trash2 size={15}/></button></span>{d.error&&<span className="doc-error">{d.error}</span>}</div>)}</div>}</>}
 {section==='ask'&&<><div className="eyebrow"><span>WORKSPACE / 03</span><span className="line"/><span>ASK & VERIFY</span><span className="mode-chip">EXTRACTIVE MODE</span></div><div className="ask-heading"><div><span className="overline">EVIDENCE WORKSPACE</span><h1>Ask. Then <em>inspect.</em></h1></div><select value={active} onChange={e=>{setActive(e.target.value);setResult(null)}} aria-label="Select source"><option value="">Select a source document</option>{docs.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><div className="question-bar"><div className="q-icon">Q</div><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')ask()}} placeholder="Ask a question grounded in this document…"/><button onClick={ask} disabled={busy||!active||question.trim().length<3}>{busy?<LoaderCircle className="spin" size={17}/>:<ArrowUpRight size={17}/>}<span>Run check</span></button></div>{!active?<div className="empty compact"><FileText size={26}/><h3>Choose a document to begin.</h3><p>Only uploaded source material can support an answer.</p><button className="button-secondary" onClick={()=>setSection('documents')}>Open document library</button></div>:<div className="workspace-grid"><section className="answer-column"><div className="panel-head"><span>01 / RESPONSE</span>{result&&<span className="mono">{result.mode?.toUpperCase()||'EXTRACTIVE'}</span>}</div>{!result?<div className="answer-empty"><div className="empty-glyph"><Sparkles size={19}/></div><h3>Your question, in context.</h3><p>Answers are assembled from retrieved source passages. Each sentence keeps a path back to the document.</p><div className="answer-note"><span>↳</span> No model-generated facts are added in local extractive mode.</div></div>:<><div className="answer-body"><span className="question-label">QUESTION</span><p className="question-echo">{result.question}</p><span className="question-label answer-label">ANSWER FROM SOURCE</span><p className="answer-text">{result.answer}</p></div><div className="claims"><div className="claims-heading"><span>CLAIM REVIEW</span><span>{result.claims.length.toString().padStart(2,'0')} CLAIMS</span></div>{result.claims.map((c,i)=><button key={i} className={`claim ${selected===i?'selected':''}`} onClick={()=>setSelected(i)}><span className="claim-no">C{i+1}</span><span className="claim-copy">{c.text}</span><span className={`status-pill ${c.status}`}>{cls(c.status)}</span></button>)}</div></>}<div className="metric-strip">{[['COVERAGE','claim_coverage'],['CITATIONS','citation_validity'],['SUPPORTED','evidence_support_rate']].map(([label,key])=><div key={key}><span>{label}</span><b>{result?`${Math.round((result.metrics[key]||0)*100)}%`:'—'}</b></div>)}</div></section>
 <section className="source-column">
  <div className="panel-head"><span>02 / SOURCE DOCUMENT</span><span className="source-title">{doc?.name||'NO SOURCE SELECTED'}</span></div>
  {doc?<>
   <div className="page-toolbar">
    <button aria-label="Previous page" onClick={()=>setPage(Math.max(1,page-1))} disabled={page<=1}><ChevronLeft size={16}/></button>
    <span>PAGE <b>{page.toString().padStart(2,'0')}</b> <i>/</i> {(doc.page_count||0).toString().padStart(2,'0')}</span>
    <button aria-label="Next page" onClick={()=>setPage(Math.min(doc.page_count,page+1))} disabled={page>=doc.page_count}><ChevronRight size={16}/></button>
    <div className="source-switch" role="group" aria-label="Source view">
     <button type="button" className={sourceMode==='pdf'?'active':''} aria-pressed={sourceMode==='pdf'} onClick={()=>setSourceMode('pdf')}>Original PDF</button>
     <button type="button" className={sourceMode==='text'?'active':''} aria-pressed={sourceMode==='text'} onClick={()=>setSourceMode('text')}>Extracted text</button>
    </div>
   </div>
   {sourceMode==='pdf'?<div className="pdf-shell"><iframe className="pdf-frame" title={`${doc.name}, page ${page} of ${doc.page_count}`} src={`${API}/documents/${encodeURIComponent(doc.id)}/file#page=${page}`} /></div>:<div className="paper"><div className="paper-top"><span>{doc.name.toUpperCase()}</span><span>PAGE {page}</span></div><div className="paper-content">{(doc.pages.find(p=>p.number===page)?.text||'No selectable text on this page.').split(/(?<=[.!?])\s+/).map((line,i)=>{const hit=result?.evidence.some(e=>e.page===page&&e.text===line);return <p key={i} className={hit?'highlighted':''}>{hit&&<i className="highlight-marker"/>}{line}</p>})}</div><div className="paper-bottom"><span>EXTRACTED TEXT / SOURCE VIEW</span><span>PL ? {page.toString().padStart(3,'0')}</span></div></div>}
  </>:<div className="source-empty">Select a source document to inspect its extracted pages.</div>}
 </section>
 <section className="verify-column"><div className="panel-head"><span>03 / VERIFICATION</span><ShieldCheck size={15}/></div>{result&&selected!==null&&result.claims[selected]?<><div className="verify-detail"><span className="question-label">CLAIM C{selected+1}</span><p>{result.claims[selected].text}</p><span className={`status-pill ${result.claims[selected].status}`}>{cls(result.claims[selected].status)}</span><h4>ASSESSMENT</h4><p className="assessment">{result.claims[selected].explanation}</p><span className="method">METHOD / {result.claims[selected].method.toUpperCase()}</span></div><div className="evidence-list"><div className="claims-heading"><span>LINKED EVIDENCE</span><span>{result.claims[selected].evidence_ids.length.toString().padStart(2,'0')}</span></div>{result.evidence.filter(e=>result.claims[selected].evidence_ids.includes(e.id)).map(e=><button key={e.id} className="evidence-card" onClick={()=>setPage(e.page)}><span className="evidence-meta">EVIDENCE {e.id.toUpperCase()} <b>PAGE {e.page}</b></span><p>{e.text}</p><span className="evidence-open">OPEN SOURCE <ArrowUpRight size={12}/></span></button>)}{!result.claims[selected].evidence_ids.length&&<div className="no-evidence"><AlertTriangle size={15}/><p>No source passage was sufficient. Treat this claim as unverified.</p></div>}</div>{result.claims[selected].warnings.map(w=><div className="warning" key={w}>{w}</div>)}</>:<div className="verify-empty"><ShieldCheck size={25}/><h3>Evidence, claim by claim.</h3><p>Run a question, then select a claim to inspect its evidence, method, and limitations.</p><div className="status-legend"><span className="supported">●</span> Supported <span className="partially_supported">●</span> Partial <span className="unverified">●</span> Unverified <span className="contradicted">●</span> Contradicted</div></div>}{result&&<a className="report-link" href={`${API}/reports/${result.id}/export`} download><Download size={14}/> Export verification report <ArrowUpRight size={13}/></a>}</section></div>}</>}
 {section==='reports'&&<><div className="eyebrow"><span>ARCHIVE / 04</span><span className="line"/><span>VERIFICATION REPORTS</span></div><div className="page-heading"><div><span className="overline">AUDIT TRAIL</span><h1>Reports & <em>findings.</em></h1><p>Each report preserves the original question, retrieved passages, and claim checks.</p></div></div>{reports.length===0?<div className="empty"><FileText size={27}/><h3>No reports yet.</h3><p>Run a question in Ask & Verify to create an inspectable report.</p><button className="button-secondary" onClick={()=>setSection('ask')}>Go to Ask & Verify</button></div>:<div className="report-list">{reports.map(r=><div className="report-row" key={r.id}><div className="report-stamp">VERIFICATION<br/>REPORT</div><div><span className="overline">{r.created_at?new Date(r.created_at).toLocaleString():''} · {r.document_id?.slice(0,8).toUpperCase()}</span><h3>{r.question}</h3><small>Report {r.id}</small></div><a href={`${API}/reports/${r.id}/export`} download><Download size={15}/> Export JSON</a></div>)}</div>}</>}
 {section==='settings'&&<><div className="eyebrow"><span>CONFIGURATION / 05</span><span className="line"/><span>WORKSPACE SETTINGS</span></div><div className="page-heading"><div><span className="overline">SYSTEM STATUS</span><h1>Clear settings.<br/><em>Honest limits.</em></h1></div></div><div className="settings-list"><div><span>API STATUS</span><b>{health?.status||'checking'}</b><small>{health?.status==='ok'?'FastAPI service is online.':health?.status==='degraded'?'FastAPI is online, but durable storage is not configured. PDF uploads are disabled.':'FastAPI service is unreachable.'}</small></div><div><span>ANSWER MODE</span><b>Extractive retrieval</b><small>Answers quote relevant source sentences. {health?.llm_configured?'An LLM credential is present, but no LLM provider is connected.':'No LLM credential is configured; extractive answers remain available.'}</small></div><div><span>OCR</span><b>Not configured</b><small>Scanned PDFs are marked unsupported; selectable text is required.</small></div><div><span>STORAGE</span><b>{health?.database==='postgres'&&health?.pdf_storage==='vercel_blob'?'Durable database and private Blob':'Durable storage not configured'}</b><small>{health?.database==='postgres'&&health?.pdf_storage==='vercel_blob'?'Documents and PDFs use connected durable storage.':'PDF uploads are disabled until Postgres and private Blob storage are connected.'}</small></div><div><span>LLM PROVIDER</span><b>{health?.llm_configured?'Credential detected':'Credentials not configured'}</b><small>Semantic entailment review is not available in this extractive setup.</small></div></div></>}
 </motion.div></AnimatePresence></main></div>{error&&<div className="toast" role="alert"><AlertTriangle size={16}/>{error}<button onClick={()=>setError('')} aria-label="Dismiss"><X size={15}/></button></div>}{busy&&<div className="busy-indicator"><LoaderCircle size={15} className="spin"/> PROCESSING SOURCE</div>}<footer className="footer"><span>PROOFLAYER © 2026</span><span>EVERY ANSWER HAS EVIDENCE. EVERY CLAIM GETS CHECKED.</span><span>{import.meta.env.PROD?'PUBLIC SHARED SESSION':'LOCAL / PRIVATE SESSION'}</span></footer></div>
}
